on: [push, pull_request]

name: Build

jobs:
  Stable:
    name: Test - stable toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Checkout Toolchain
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Running test script
        env:
          DO_LINT: true
          DO_DOCS: true
          DO_FEATURE_MATRIX: true
        run: cargo build --all

  Arch32bit:
    name: Test 32-bit version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Add architecture i386
        run: sudo dpkg --add-architecture i386
      - name: Install i686 gcc
        run: sudo apt-get update -y && sudo apt-get install -y gcc-multilib
      - name: Install target
        run: rustup target add i686-unknown-linux-gnu
      - name: Run test on i686
        run: cargo build --target i686-unknown-linux-gnu

  Cross:
    name: Cross test
    if: ${{ !github.event.act }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install i686 gcc
        run: sudo apt-get update -y && sudo apt install llvm-dev libclang-dev clang
      - name: Install target
        run: rustup target add s390x-unknown-linux-gnu
      - name: install cross
        run: cargo install cross --locked
      - name: run cross test
        run: cross test --target s390x-unknown-linux-gnu

  WASM:
    name: WASM
    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Crate
#        uses: actions/checkout@v3
#      - name: Checkout Toolchain
#        uses: dtolnay/rust-toolchain@stable
#      - name: Install clang
#        run: sudo apt install llvm-dev libclang-dev -y clang
#      - name: Running WASM
#        run: clang --version && CARGO_TARGET_DIR=wasm cargo install --force wasm-pack && CC=clang wasm-pack build
#    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "LIBCLANG_PATH=$PWD/upstream/libclang" >> $GITHUB_ENV
          source ./emsdk_env.sh

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target wasm32-unknown-unknown

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-unknown-unknown

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target wasm32-unknown-unknown
